//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityPos
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_verificador
    {
        public int id { get; set; }
        public string autoDocumento { get; set; }
        public string codigoUsuarioVer { get; set; }
        public string nombreUsuarioVer { get; set; }
        public string estatusVer { get; set; }
        public string estatusAnulado { get; set; }
        public System.DateTime fechaVer { get; set; }
    
        public virtual ventas ventas { get; set; }
    }
}
